### ISSUE TITLE
Batching INSERT .. RETURNING fails with 'TypeError: this.parseRow is not a function'

### ISSUE THREAD

**Issue by bjorm** [mariadb-corporation/mariadb-connector-nodejs#102]
```
/home/bmo/work/repos/mariadb-returning-bug/node_modules/mariadb/lib/cmd/resultset.js:376
    const row = this.parseRow(this._columns, packet, opts);
                     ^

TypeError: this.parseRow is not a function
    at BatchBulk.readResultSetRow (/home/bmo/work/repos/mariadb-returning-bug/node_modules/mariadb/lib/cmd/resultset.js:376:22)
    at PacketInputStream.receivePacketBasic (/home/bmo/work/repos/mariadb-returning-bug/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/home/bmo/work/repos/mariadb-returning-bug/node_modules/mariadb/lib/io/packet-input-stream.js:160:20)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

This should allow you to reproduce it:
```javascript
const mariadb = require('mariadb')

let pool

try {
    pool = mariadb.createPool({
        host: 'localhost',
        user: 'root',
        password: 'blabla',
        database: 'bla',
        connectionLimit: 5
    })
} catch (error) {
    console.error(error)
    process.exit(1)
}

const run = async () => {
    let con;
    try {
        con = await pool.getConnection()
        await con.query('drop table bar')
        await con.query('create table bar (id bigint not null primary key)')
        console.log(await con.batch('insert into bar (id) values (?) returning id', [[1], [2], [3], [4]]))
    }  finally {
        if (con) {
            await con.release()
        }
        if (pool) {
            await pool.end()
        }
    }
}

run()
```
Would RETURNING even be supported for batched statements?

**Comment by rusher** [comment]
10.5 new features permit returning. 
BULK insert + RETURNING will permit having fast batch returning all ids.
That's definitively a must have feature, and i'm currently working on implementing that

**Comment by rusher** [comment]
waiting to correction of https://jira.mariadb.org/browse/MDEV-21916 first

**Comment by rusher** [comment]
correction will be in next 3.0.1-rc release (https://jira.mariadb.org/browse/CONJS-125)
