### ISSUE TITLE
Is there a way to create a trigger with multiple statements inside? (Delimiter issue)

### ISSUE THREAD

**Issue by rvalenca** [mariadb-corporation/mariadb-connector-nodejs#147]
Hello,

We all know that in MySQL/MariaDB, in case we want to create a trigger with multiple statements inside, we need to make use of the "DELIMITER". Ex.:

```
delimiter $$
create or replace trigger trigger1 after insert on table1 for each row
begin \
  declare _var1 int(11);
  select a into _var1 from table1;
end$$ \
delimiter ;
```

If we try to execute such a statement via conn.query, we get the following error:

err: SqlError: (conn=11, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delimiter $$       create or replace trigger trigger1 after insert on table1 ...' at line 1
sql: delimiter $$       create or replace trigger trigger1 after insert on table1 for each row       begin         declare _var1 int(11);                 select a into _var1 from table1;               end$$       delimiter ; - parameters:[]
    at Object.module.exports.createError (/opt/IBM/tivoli/netcool/tools/mariadb-test/node_modules/mariadb/lib/misc/errors.js:55:10)
    at PacketNodeEncoded.readError (/opt/IBM/tivoli/netcool/tools/mariadb-test/node_modules/mariadb/lib/io/packet.js:505:19)
    at Query.readResponsePacket (/opt/IBM/tivoli/netcool/tools/mariadb-test/node_modules/mariadb/lib/cmd/resultset.js:46:28)
    at PacketInputStream.receivePacketBasic (/opt/IBM/tivoli/netcool/tools/mariadb-test/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/opt/IBM/tivoli/netcool/tools/mariadb-test/node_modules/mariadb/lib/io/packet-input-stream.js:169:20)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  fatal: false,
  errno: 1064,
  sqlState: '42000',
  code: 'ER_PARSE_ERROR'
}

Is there a way to work around this?
The only way I found out is to execute it with mysql client command directly through Node, but then why to have a npm lib, right?

Thanks in advance,

**Comment by rvalenca** [comment]
ok, just figured it out.

If the delimiter lines are removed, somehow it works fine (even though it does not work via a SQL client). So:

```
create or replace trigger trigger1 after insert on table1 for each row
begin
  declare _var1 int(11);
  select a into _var1 from table1;
end
```
