### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'leaked')

### ISSUE THREAD

**Issue by iamDonkey** [mariadb-corporation/mariadb-connector-nodejs#206]
```
/root/node_modules/mariadb/lib/pool.js:439
      if (value.leaked) counter++;
                ^

TypeError: Cannot read properties of null (reading 'leaked')
    at Pool._leakedConnections (/root/node_modules/mariadb/lib/pool.js:439:17)
    at Pool._errorMsgAddon (/root/node_modules/mariadb/lib/pool.js:446:118)
    at Timeout._onTimeout (/root/node_modules/mariadb/lib/pool.js:162:69)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7)
```

found this in my logs don't know what does this mean.

**Comment by rusher** [comment]
this is a regression after enhancement https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/94be5e86175d36dacd063998da878d18dc4d6c21.
