### ISSUE TITLE
Sequelize delete property of meta object error

### ISSUE THREAD

**Issue by knoxcard2** [mariadb-corporation/mariadb-connector-nodejs#234]
/etc/nginx/domains/buycanna.io/node_modules/sequelize/lib/dialects/mariadb/query.js:110
    ```  
        delete data.meta;
    ```

TypeError: Cannot delete property 'meta' of [object Array]
    at Query.formatResults (/etc/nginx/domains/buycanna.io/node_modules/sequelize/lib/dialects/mariadb/query.js:110:7)
    at Query.run (/etc/nginx/domains/buycanna.io/node_modules/sequelize/lib/dialects/mariadb/query.js:73:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /etc/nginx/domains/buycanna.io/node_modules/sequelize/lib/sequelize.js:314:16

Node.js v19.6.1

**Comment by PeppeL-G** [comment]
This rather looks like a problem with the [sequelize](https://www.npmjs.com/package/sequelize) package?

**Comment by WikiRik** [comment]
It is, sequelize does not support v3 of this connector yet. Almost all tests of the sequelize package pass on 3.0.2 but more fail on 3.1.0 due to the non-enumerable meta. The advice of the sequelize team is to not upgrade to v3 of the mariadb connector until v7 of sequelize

**Comment by rusher** [comment]
do you have some link @WikiRik ? correction is easy to do, and i can make a PR

**Comment by WikiRik** [comment]
> do you have some link @WikiRik / @knoxcard2 ? correction is easy to do, and i can make a PR

You can check out which tests are failing in this renovate PR; https://github.com/sequelize/sequelize/pull/15311

**Comment by rusher** [comment]
[from Rik Smale](https://jira.mariadb.org/browse/CONJS-243?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=262503#comment-262503 ) :

> Starting with v7.0.0-alpha27 (released soon) sequelize will support 3.x. See https://github.com/sequelize/sequelize/pull/16139
> Support for 3.x is not planned for sequelize v6 at this moment

**Comment by WikiRik** [comment]
Ah yes, I forgot this issue was open as well. Thanks for posting it here!

**Comment by joacub** [comment]
it is supported now ?
