### ISSUE TITLE
3.2.2 Packets out of Order error inserting large document on Linux. Same code works with 2.5.6 on Linux and 3.2.2. on Windows

### ISSUE THREAD

**Issue by markddrake** [mariadb-corporation/mariadb-connector-nodejs#257]
Getting  "Got packets out of order" inserting large document into MariaDB after upgrading to 3.2.2. As can be seen below the same code works perfectly after downgrading to 2.5.6. No other changes.

MAX_ALLOWED_PACKET is set to the maximum value.

```
C:\Development\YADAMU\src>mysql -uroot -poracle -hyadamu-db2 -P3307 -D mysql
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2007
Server version: 11.1.2-MariaDB-1:11.1.2+maria~ubu2204 mariadb.org binary distribution

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT @@max_allowed_packet
    -> ;
+----------------------+
| @@max_allowed_packet |
+----------------------+
|           1073741824 |
+----------------------+
1 row in set (0.00 sec)

mysql>
```
Running my regression test with 3.2.2

```
C:\Development\YADAMU>docker exec -it YADAMU-DEV bash
root@732499e434cc:/usr/src/YADAMU# copy qa/regression/co
connections.json      copyPerformance.json
root@732499e434cc:/usr/src/YADAMU# copy qa/regression/connections.json work
bash: copy: command not found
root@732499e434cc:/usr/src/YADAMU# cp qa/regression/connections.json work
root@732499e434cc:/usr/src/YADAMU# cp qa/regression/tasks.json work
root@732499e434cc:/usr/src/YADAMU# qa/bin/test.sh work/impDataTypes.json
2023-10-31T19:12:31.274Z [QA][Environemnt][x64][linux][v20.8.0]: Running tests
2023-10-31T19:12:31.413Z [INFO][READER][YABASC][3.0][Manager]: Ready.
2023-10-31T19:12:31.416Z [INFO][WRITER][MariaDB][11.1.2][DATA_ONLY][Manager]: Ready.
2023-10-31T19:12:31.453Z [INFO][YABASC][READER]: Processing file "/usr/src/YADAMU/stagingArea/export/json/postgres/postgresTypes.json". Size 52720072 bytes.
2023-10-31T19:12:31.469Z [INFO][FILE]: Operations restricted to the following tables: ["character_types"].
2023-10-31T19:12:31.522Z [DDL][MariaDB]: Generated 1 "Create Table" statements and 1 DML statements. Elapsed time: 00:00:00.012s.
2023-10-31T19:12:31.555Z [DDL][MariaDB]: Executed 1 DDL operations. Elapsed time: 00:00:00.032s.
2023-10-31T19:12:32.727Z [INFO][RECONNECT][MariaDB][SQL]: Connection Lost: Attemping reconnection.
2023-10-31T19:12:32.727Z [WARNING][RECONNECT][MariaDB][SQL]: write ECONNRESET
2023-10-31T19:12:32.731Z [INFO][RECONNECT][MariaDB][SQL]: Exception logged to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.32.727Z.trace".
2023-10-31T19:12:32.736Z [INFO][RECONNECT][MariaDB][SQL]: New connection available.
2023-10-31T19:12:33.334Z [WARNING][MariaDB][character_types][INSERT MANY][Batch][1][4]: Got packets out of order
2023-10-31T19:12:33.336Z [INFO][MariaDB][character_types][INSERT MANY][Batch][1][4]: Exception logged to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.334Z.trace".
2023-10-31T19:12:33.337Z [INFO][RECONNECT][MariaDB][SQL]: Connection Lost: Attemping reconnection.
2023-10-31T19:12:33.337Z [WARNING][RECONNECT][MariaDB][SQL]: socket has unexpectedly been closed
2023-10-31T19:12:33.338Z [INFO][RECONNECT][MariaDB][SQL]: Exception logged to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.337Z.trace".
2023-10-31T19:12:33.338Z [INFO][YABASC][WRITER]: Writing data to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.334Z.data".
2023-10-31T19:12:33.467Z [INFO][RECONNECT][MariaDB][SQL]: New connection available.
2023-10-31T19:12:33.467Z [WARNING][MariaDB][character_types][Batch]: Switching to Iterative mode.
2023-10-31T19:12:33.995Z [ERROR][REJECTED][MariaDB][character_types][INSERT ONE][0][0]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD-ABCD...' at line 1
2023-10-31T19:12:33.996Z [INFO][REJECTED][MariaDB][character_types][INSERT ONE][0][0]: Exception logged to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.995Z.trace".
2023-10-31T19:12:34.121Z [INFO][YABASC][WRITER]: Writing data to "/usr/src/YADAMU/rejections/rejection_2023-10-31T19.12.31.467Z.json".
2023-10-31T19:12:34.278Z [INFO][YABASC][WRITER]: Writing data to "/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.995Z.data".
2023-10-31T19:12:37.043Z [WARNING][character_types][Iterative]: Read 4. Written 3. Skipped 1. Reader Elapsed Time: 00:00:00.457s. Throughput 9 rows/s. Writer Elapsed Time: 00:00:05.568s.  Idle Time: 00:00:00.000s. SQL Exection Time: 00:00:00.000s. Throughput: 1 rows/s.
2023-10-31T19:12:37.046Z [ERROR][YADAMU][TEST]: Operation completed with 1 errors and 5 warnings. Elapsed time: 00:00:05.765.
2023-10-31T19:12:37.048Z [INFO][REJECTIONS]: 1 records written to "/usr/src/YADAMU/rejections/rejection_2023-10-31T19.12.31.467Z.json"

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                    TARGET SCHEMA |                                       TABLE_NAME |      ROWS READ |        SKIPPED |        WRITTEN |          COUNT |          DELTA |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                       t_postgres |                                  character_types |              4 |              1 |              3 |              3 |              0 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

2023-10-31T19:12:37.054Z [QA][IMPORT][COPY][file://"export/json/postgres/postgresTypes.json"][mariadb#1://"t_postgres"]: Errors: 1. Warnings: 5. Failed: 0. Elapsed Time: 00:00:05.684s.

+-------------------------------------------------------------------------------+
|          Data Set |   Step |      Mode |    Source |    Target | Elapsed Time |
+-------------------------------------------------------------------------------+
| postgresDataTypes | IMPORT | DATA_ONLY |      file | mariadb#1 | 00:00:05.678 |
| postgresDataTypes |  COUNT |           | mariadb#1 |           | 00:00:00.001 |
| postgresDataTypes |  TOTAL |           |      file | mariadb#1 | 00:00:05.684 |
+-------------------------------------------------------------------------------+

2023-10-31T19:12:37.055Z [QA][IMPORT][TASK][file://export/json/postgres][mariadb#1][postgresDataTypes]: Errors: 1. Warnings: 5. Failed: 0. Elapsed Time: 00:00:05.779s
2023-10-31T19:12:37.055Z [QA][IMPORT][TARGET][file://export/json/postgres][mariadb#1]: Errors: 1. Warnings: 5. Failed: 0. Elapsed Time: 00:00:05.779s
2023-10-31T19:12:37.055Z [QA][IMPORT][TEST][file://export/json/postgres]: Errors: 1. Warnings: 5. Failed: 0. Elapsed Time: 00:00:05.780s

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                 End Time | Operation |                      Source |    Target |              Task |      Results |                                                         Memory Usage | Elapsed Time |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:12:37.055Z |    IMPORT | file://export/json/postgres |           |                   |  1 |  5 |  0 |  179,462,144 |  91,037,696 |  54,097,008 |  19,194,896 |  16,854,318 | 00:00:05.780 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                 End Time | Operation |                      Source |    Target |              Task |      Results |                                                         Memory Usage | Elapsed Time |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:12:37.055Z |    IMPORT | file://export/json/postgres | mariadb#1 | postgresDataTypes |  1 |  5 |  0 |  179,462,144 |  91,037,696 |  54,088,032 |  19,194,856 |  16,854,318 | 00:00:05.779 |
| 2023-10-31T19:12:37.055Z |    IMPORT | file://export/json/postgres | mariadb#1 |                   |  1 |  5 |  0 |  179,462,144 |  91,037,696 |  54,093,392 |  19,194,896 |  16,854,318 | 00:00:05.779 |
| 2023-10-31T19:12:37.055Z |    IMPORT | file://export/json/postgres |           |                   |  1 |  5 |  0 |  179,462,144 |  91,037,696 |  54,097,008 |  19,194,896 |  16,854,318 | 00:00:05.780 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:12:37.055Z |           |                             |           |                   |  1 |  5 |  0 |  179,462,144 |  91,037,696 |  54,098,456 |  19,194,896 |  16,854,318 | 00:00:05.780 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

2023-10-31T19:12:37.092Z [QA][YADAMU][REGRESSION][work/impDataTypes.json]: Errors: 1. Warnings: 5. Failed: 0. Elapsed Time: 00:00:05.818s.
root@732499e434cc:/usr/src/YADAMU# cd src
root@732499e434cc:/usr/src/YADAMU/src# npm ls
yadamu@1.0.0 /usr/src/YADAMU
+-- @azure/storage-blob@12.16.0
+-- @electron/remote@2.0.12
+-- aws-sdk@2.1483.0
+-- bootstrap-icons@1.11.1
+-- bootstrap@5.3.2
+-- cookie-parser@1.4.6
+-- csv-parser@3.0.0
+-- electron-packager@17.1.2
+-- electron@21.4.4
+-- express-session@1.17.3
+-- express@4.18.2
+-- font-awesome@4.7.0
+-- ibm_db_electron@npm:ibm_db@3.2.2
+-- ibm_db@3.2.2
+-- install@0.13.0
+-- jquery@3.7.1
+-- mariadb@3.2.2
+-- mime-types@2.1.35
+-- mongodb@6.2.0
+-- mssql@10.0.1
+-- mysql@2.18.1
+-- npm@8.19.4
+-- oracledb@6.2.0
+-- pg-copy-streams@6.0.6
+-- pg-query-stream@4.5.3
+-- pg@8.11.3
+-- readable-stream@4.4.2
+-- snowflake-sdk@1.9.0
+-- uuid@9.0.1
`-- wkx@0.5.0

````

Downgrade to 2.5.6

```
root@732499e434cc:/usr/src/YADAMU/src# npm install mariadb@2.5.6
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.8.0', npm: '10.1.0' }
npm WARN EBADENGINE }

added 2 packages, removed 1 package, changed 1 package, and audited 910 packages in 4s

100 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
root@732499e434cc:/usr/src/YADAMU/src# npm ls
yadamu@1.0.0 /usr/src/YADAMU
+-- @azure/storage-blob@12.16.0
+-- @electron/remote@2.0.12
+-- aws-sdk@2.1483.0
+-- bootstrap-icons@1.11.1
+-- bootstrap@5.3.2
+-- cookie-parser@1.4.6
+-- csv-parser@3.0.0
+-- electron-packager@17.1.2
+-- electron@21.4.4
+-- express-session@1.17.3
+-- express@4.18.2
+-- font-awesome@4.7.0
+-- ibm_db_electron@npm:ibm_db@3.2.2
+-- ibm_db@3.2.2
+-- install@0.13.0
+-- jquery@3.7.1
+-- mariadb@2.5.6
+-- mime-types@2.1.35
+-- mongodb@6.2.0
+-- mssql@10.0.1
+-- mysql@2.18.1
+-- npm@8.19.4
+-- oracledb@6.2.0
+-- pg-copy-streams@6.0.6
+-- pg-query-stream@4.5.3
+-- pg@8.11.3
+-- readable-stream@4.4.2
+-- snowflake-sdk@1.9.0
+-- uuid@9.0.1
`-- wkx@0.5.0
```

Regresson Test Works

```
root@732499e434cc:/usr/src/YADAMU/src# cd ..
root@732499e434cc:/usr/src/YADAMU# qa/bin/test.sh work/impDataTypes.json
2023-10-31T19:13:47.380Z [QA][Environemnt][x64][linux][v20.8.0]: Running tests
2023-10-31T19:13:47.498Z [INFO][READER][YABASC][3.0][Manager]: Ready.
2023-10-31T19:13:47.499Z [INFO][WRITER][MariaDB][11.1.2][DATA_ONLY][Manager]: Ready.
2023-10-31T19:13:47.526Z [INFO][YABASC][READER]: Processing file "/usr/src/YADAMU/stagingArea/export/json/postgres/postgresTypes.json". Size 52720072 bytes.
2023-10-31T19:13:47.540Z [INFO][FILE]: Operations restricted to the following tables: ["character_types"].
2023-10-31T19:13:47.574Z [DDL][MariaDB]: Generated 1 "Create Table" statements and 1 DML statements. Elapsed time: 00:00:00.007s.
2023-10-31T19:13:47.612Z [DDL][MariaDB]: Executed 1 DDL operations. Elapsed time: 00:00:00.037s.
2023-10-31T19:13:50.340Z [INFO][character_types][Batch]: Rows 4. Reader Elapsed Time: 00:00:00.385s. Throughput 10 rows/s. Writer Elapsed Time: 00:00:02.795s.  Idle Time: 00:00:00.000s. SQL Exection Time: 00:00:00.000s. Throughput: 1 rows/s.
2023-10-31T19:13:50.345Z [INFO][YADAMU][TEST]: Operation completed successfully. Elapsed time: 00:00:02.960.

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                    TARGET SCHEMA |                                       TABLE_NAME |      ROWS READ |        SKIPPED |        WRITTEN |          COUNT |          DELTA |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                       t_postgres |                                  character_types |              4 |              0 |              4 |              4 |              0 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

2023-10-31T19:13:50.352Z [QA][IMPORT][COPY][file://"export/json/postgres/postgresTypes.json"][mariadb#1://"t_postgres"]: Errors: 0. Warnings: 0. Failed: 0. Elapsed Time: 00:00:02.884s.

+-------------------------------------------------------------------------------+
|          Data Set |   Step |      Mode |    Source |    Target | Elapsed Time |
+-------------------------------------------------------------------------------+
| postgresDataTypes | IMPORT | DATA_ONLY |      file | mariadb#1 | 00:00:02.877 |
| postgresDataTypes |  COUNT |           | mariadb#1 |           | 00:00:00.001 |
| postgresDataTypes |  TOTAL |           |      file | mariadb#1 | 00:00:02.884 |
+-------------------------------------------------------------------------------+

2023-10-31T19:13:50.353Z [QA][IMPORT][TASK][file://export/json/postgres][mariadb#1][postgresDataTypes]: Errors: 0. Warnings: 0. Failed: 0. Elapsed Time: 00:00:02.972s
2023-10-31T19:13:50.353Z [QA][IMPORT][TARGET][file://export/json/postgres][mariadb#1]: Errors: 0. Warnings: 0. Failed: 0. Elapsed Time: 00:00:02.972s
2023-10-31T19:13:50.353Z [QA][IMPORT][TEST][file://export/json/postgres]: Errors: 0. Warnings: 0. Failed: 0. Elapsed Time: 00:00:02.972s

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                 End Time | Operation |                      Source |    Target |              Task |      Results |                                                          Memory Usage | Elapsed Time |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:13:50.353Z |    IMPORT | file://export/json/postgres |           |                   |  0 |  0 |  0 |  234,954,752 |  101,711,872 |  65,665,200 |  80,027,146 |  77,686,568 | 00:00:02.972 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                 End Time | Operation |                      Source |    Target |              Task |      Results |                                                          Memory Usage | Elapsed Time |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:13:50.353Z |    IMPORT | file://export/json/postgres | mariadb#1 | postgresDataTypes |  0 |  0 |  0 |  234,954,752 |  101,711,872 |  65,656,248 |  80,027,106 |  77,686,568 | 00:00:02.972 |
| 2023-10-31T19:13:50.353Z |    IMPORT | file://export/json/postgres | mariadb#1 |                   |  0 |  0 |  0 |  234,954,752 |  101,711,872 |  65,661,608 |  80,027,146 |  77,686,568 | 00:00:02.972 |
| 2023-10-31T19:13:50.353Z |    IMPORT | file://export/json/postgres |           |                   |  0 |  0 |  0 |  234,954,752 |  101,711,872 |  65,665,200 |  80,027,146 |  77,686,568 | 00:00:02.972 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-10-31T19:13:50.353Z |           |                             |           |                   |  0 |  0 |  0 |  234,954,752 |  101,711,872 |  65,666,648 |  80,027,146 |  77,686,568 | 00:00:02.973 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

2023-10-31T19:13:50.379Z [QA][YADAMU][REGRESSION][work/impDataTypes.json]: Errors: 0. Warnings: 0. Failed: 0. Elapsed Time: 00:00:02.999s.
root@732499e434cc:/usr/src/YADAMU#
```

Trace file 
```
root@732499e434cc:/usr/src/YADAMU# cat /usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.334Z.trace
2023-10-31T19:12:33.334Z [WARNING][MariaDB][character_types][INSERT MANY][Batch][1][4]: Got packets out of order
BatchInsertError: Got packets out of order
    at YadamuError.createBatchException (file:///usr/src/YADAMU/src/node/core/yadamuException.js:61:14)
    at MariadbWriter.createBatchException (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:224:21)
    at MariadbWriter.reportBatchError (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:234:33)
    at MariadbWriter.reportBatchError (file:///usr/src/YADAMU/src/node/dbi/mariadb/mariadbWriter.js:50:8)
    at MariadbWriter._writeBatch (file:///usr/src/YADAMU/src/node/dbi/mariadb/mariadbWriter.js:73:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MariadbWriter.processBatch (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:295:23)
    at async MariadbWriter.doWrite (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:371:6) {
  cause: MariadbError: Got packets out of order
  sql: insert into "t_postgres"."character_types" ("character_col","character_varying_col","character_max_col","character_varying_max_col","character_4000_col","character_varying_4000_col","character_64k_col","character_varying_64k_col","text_col") values  (?,?,?...
      at MariadbQA.executeSQL (file:///usr/src/YADAMU/src/node/dbi/mariadb/mariadbDBI.js:250:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      ... 2 lines matching cause stack trace ...
      at async MariadbWriter.doWrite (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:371:6) {
    _DRIVER_ID: 318.8357877731323,
    cause: SqlError: Got packets out of order
    sql: insert into "t_postgres"."character_types" ("character_col","character_varying_col","character_max_col","character_varying_max_col","character_4000_col","character_varying_4000_col","character_64k_col","character_varying_64k_col","text_col") values  (?,?,?...
        at module.exports.createError (/usr/src/YADAMU/node_modules/mariadb/lib/misc/errors.js:64:10)
        at Query.throwError (/usr/src/YADAMU/node_modules/mariadb/lib/cmd/command.js:99:22)
        at Query.readResponsePacket (/usr/src/YADAMU/node_modules/mariadb/lib/cmd/parser.js:62:21)
        at PacketInputStream.receivePacketBasic (/usr/src/YADAMU/node_modules/mariadb/lib/io/packet-input-stream.js:85:9)
        at PacketInputStream.onData (/usr/src/YADAMU/node_modules/mariadb/lib/io/packet-input-stream.js:135:20)
        at Socket.emit (node:events:514:28)
        at addChunk (node:internal/streams/readable:376:12)
        at readableAddChunk (node:internal/streams/readable:349:9)
        at Readable.push (node:internal/streams/readable:286:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
     From event:
        at ConnectionPromise._PARAM (/usr/src/YADAMU/node_modules/mariadb/lib/connection-promise.js:106:30)
        at ConnectionPromise.query (/usr/src/YADAMU/node_modules/mariadb/lib/connection-promise.js:92:40)
        at MariadbQA.executeSQL (file:///usr/src/YADAMU/src/node/dbi/mariadb/mariadbDBI.js:251:47)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async MariadbWriter._writeBatch (file:///usr/src/YADAMU/src/node/dbi/mariadb/mariadbWriter.js:65:27)
        at async MariadbWriter.processBatch (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:295:23)
        at async MariadbWriter.doWrite (file:///usr/src/YADAMU/src/node/dbi/base/yadamuWriter.js:371:6) {
      sqlMessage: 'Got packets out of order',
      sql: 'insert into "t_postgres"."character_types" ("character_col","character_varying_col","character_max_col","character_varying_max_col","character_4000_col","character_varying_4000_col","character_64k_col","character_varying_64k_col","text_col") values  (?,?,?...',
      fatal: true,
      errno: 1156,
      sqlState: '08S01',
      code: 'ER_NET_PACKETS_OUT_OF_ORDER'
    },
    sql: 'insert into "t_postgres"."character_types" ("character_col","character_varying_col","character_max_col","character_varying_max_col","character_4000_col","character_varying_4000_col","character_64k_col","character_varying_64k_col","text_col") values  (?,?,?,?,?,?,?,?,?),(...),(?,?,?,?,?,?,?,?,?)',
    tags: []
  },
  tableName: 'character_types',
  batchNumber: 1,
  batchSize: 0,
  columnNames: [
    'character_col',
    'character_varying_col',
    'character_max_col',
    'character_varying_max_col',
    'character_4000_col',
    'character_varying_4000_col',
    'character_64k_col',
    'character_varying_64k_col',
    'text_col'
  ],
  targetDataTypes: [
    'char',       'longtext',
    'mediumtext', 'mediumtext',
    'varchar',    'varchar',
    'text',       'text',
    'longtext'
  ],
  dataFilePath: '/usr/src/YADAMU/exceptions/exception_2023-10-31T19.12.33.334Z.data'
```
Code is running in a docker container build from the official node image.  Same code runs without errors with the 3.2.2. library from Windows. 

Before I spend time creating a debuggable test case , I was wondering if this is a known issue, or if there is something that needs to be configured to work with large documents, other than max_allowed_packet |

**Comment by markddrake** [comment]
Works on Linux with 3.0.2. Fails with 3.1.2

**Comment by markddrake** [comment]
Fails with the same error on 3.0.2 and 3.1.2.

**Comment by markddrake** [comment]
Attempted to convert to the new 'batch' operation and ran into #258 and #259

**Comment by markddrake** [comment]
Opened https://github.com/mariadb-corporation/mariadb-connector-nodejs/issues/273 against mariadb@3.2.3 with testcase
