### ISSUE TITLE
batch Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by endingisnight** [mariadb-corporation/mariadb-connector-nodejs#299]
server version: 11.5.2-1
connector: 3.4.0
```js
const config = require(`./config.json`).db;
const maria = require(`mariadb/callback`);
globalThis.sql = maria.createPool({
    host: config.host,
    user: config.user,
    password: config.pass,
    database: `debug`,
})

// DROP TABLE IF EXISTS tab; CREATE TABLE tab (a JSON, b JSON, c LONGTEXT);
let vals = require(`./data.json`)
console.log(vals.flatMap(x => Buffer.from(x).byteLength));

// with query it works, but not with batch :)
sql.batch(
    `INSERT INTO tab (a,b,c) VALUES (?,?,?)`,
    vals, async (err, res) => {
        if (err) throw err;
        console.log(res);
        process.exit(0);
    })
```
[data.json](https://github.com/user-attachments/files/17609161/data.json) is 19MB so you'll have to increase max_allowed_packet from it's default 16MB

```
node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/cmd/batch-bulk.js:74
      const val = value[i];
                       ^

TypeError: Cannot read properties of undefined (reading '0')
    at BatchBulk.parameterHeaderFromValue (node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/cmd/batch-bulk.js:74:24)
    at BatchBulk.sendComStmtBulkExecute (node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/cmd/batch-bulk.js:306:38)
    at BatchBulk.start (node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/cmd/batch-bulk.js:60:10)
    at Connection.addCommandEnablePipeline (node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/connection.js:1151:11)
    at Connection.executeBulkPromise (node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/connection.js:290:10)
    at new Promise (<anonymous>)
    at node_modules/.pnpm/mariadb@3.4.0/node_modules/mariadb/lib/connection.js:214:16
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v23.1.0
```

For me, removing the "!" [here](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/24a58245cba201da91f41f7f96f8dd165d31c6c7/lib/cmd/batch-bulk.js#L300) fixed it.

**Comment by rusher** [comment]
will be part of 3.4.1 release
